INVALID_COMMAND = "Invalid command. Type 'help' to get the list of valid commands. "
EMPTY_PHONEBOOK = "Your phone book is empty. Let's add some contacts"
ABORTED = "Aborted"
YES_NO_CHOICE = " yes/no >>> "
YES_CHOICE = "yes"
NO_CHOICE = "no"
